### PR TITLE
Multiplatform support

### PR DESCRIPTION
**Pull request by James-Livesey**
This PR addresses #1 by allowing the OS bootstrapping process to target multiple types of platform, as opposed to just x86-64. This will make way for us being able to produce builds for ARM architectures and other chipsets, in addition to other platforms, like the Raspberry Pi and PinePhone.

For example, to build for x86-64, you can supply the optional platform type argument:

```bash
./bootstrap.sh x86_64
```

### CODE REVIEW

**Comment by James-Livesey** [comment]
Still needing to test to see if this works! I've got some test equipment (such as Raspberry Pis) to bring with me back to London so I'll be able to see if LiveG OS builds work on that equipment.

**Comment by James-Livesey** [comment]
Confirmed bootable on Raspberry Pi, though more tweaking to make the OS experience more user-friendly is needed down the line.

To run (`--no-emulation` recommended):
```
./bootstrap.sh rpi
```

**Comment by James-Livesey** [comment]
@sd0e @tramcrazy What do you think? Only done for Raspberry Pi for now, but we can do building for PinePhone soon!

**Comment by James-Livesey** [comment]
We might need to test for the original `x86_64` to see if that still builds with these new changes, but not critical atm.

**Comment by sd0e** [comment]
Nice! I'm getting the following error on WSL though even after installing prerequisites, is this just a WSL thing?
image

**Comment by James-Livesey** [comment]
Looks like it's just an issue with `qemu-img` not existing from what I can see! Try `apt` installing `qemu-utils` (might need to add that to the readme).

I think most of the other errors after that are just follow-on errors from that issue. Though note that some errors to do with unmounting etc. are expected just to ensure that the image is already unmounted before mounting it again.

**Comment by James-Livesey** [comment]
Think @sd0e you were happy with this when I saw you, so going to merge this in now!

**Comment by James-Livesey** [comment]
Will keep the branch open for future development of multiplatform support (eg. supporting a new platform).

Edit: I think I just wrote the same thing again in the brackets lol

**Pull request merged**
